spring:
  application:
    name: alpr
  datasource:
    url: jdbc:postgresql://localhost:5432/sentinela
    username: sentinela
    password: sentinela
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  security:
    jwt:
      secret: ${JWT_SECRET:dev-secret-change-me-please-32bytes-minimum!!}
      access-ttl: 15m
      refresh-ttl: 7d

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
